#!/bin/sh

cd ~/.config/PlutoWM/dwm
rm -v -f config.h
make
make clean install

cd ~/.config/PlutoWM/st
rm -v -f config.h
make
make clean install

cd ~/.config/PlutoWM/scroll
rm -v -f config.h
make
make clean install

cd ~/.config/PlutoWM/dmenu
rm -v -f config.h
make
make clean install